FROM apache/superset:latest

USER root

RUN pip install psycopg2

ENV ADMIN_USERNAME $SUPERSET_ADMIN_USERNAME
ENV ADMIN_EMAIL $SUPERSET_ADMIN_EMAIL
ENV ADMIN_PASSWORD $SUPERSET_ADMIN_PASSWORD

COPY ./superset-init.sh /superset-init.sh

COPY superset_config.py /app/
ENV SUPERSET_CONFIG_PATH /app/superset_config.py

USER superset
ENTRYPOINT [ "/superset-init.sh" ]