# This file is for the server to run all the needed services.
version: '3.8'

# This part of the code lists all the services and their specifications.
services:
  # We are using postgres as our database service.
  # The specifications can be edited at this part.
  postgres_db:
    image: postgres:latest
    container_name: database
    restart: always
    env_file:
    - .env
    ports:
      - 5432:5432
    volumes:
      - postgres_db:/var/lib/postgresql/database

  # We are using pgadmin as a configuration service for the database to have a nice overview.
  pg_admin:
    image: dpage/pgadmin4
    container_name: db_config
    restart: always
    ports:
      - 2000:80
    env_file:
      - .env
    volumes:
      - pg_admin:/var/lib/pg_admin
    depends_on:
      - postgres_db

  # Superset is used for the bi&a system and is something like a frontend of the server.
  superset:
    container_name: bia
    build: ./ApacheSuperset
    env_file:
      - .env
    ports:
      - 8088:8088
    depends_on:
      - postgres_db

  # This is the backend running on a Django web app.
  server-backend:
    container_name: backend
    restart: always
    build: ./Backend/Server/server_backend/
    env_file:
      - .env
    ports:
      - 9000:9000
    depends_on:
      - postgres_db

# This specifies the place where the data is stored of the database.
volumes:
  postgres_db:
    driver: local
  pg_admin:
    driver: local