# This file is for the server to run all the needed services.
version: '3.8'

# This part of the code lists all the services and their specifications.
services:
  # We are using postgres as our database service.
  # The specifications can be edited at this part.
  postgres_db:
    image: postgres:latest
    container_name: database
    restart: always
    env_file:
    - config.env
    ports:
      - 5432:5432
    volumes:
      - postgres_db:/var/lib/postgresql/database

  # We are using pgadmin as a configuration service for the database to have a nice overview.
  pg_admin:
    image: dpage/pgadmin4
    container_name: db_config
    restart: always
    ports:
      - 2000:80
    env_file:
      - config.env
    volumes:
      - pg_admin:/var/lib/pg_admin
    depends_on:
      - postgres_db

  # Superset is used for the bi&a system and is something like a frontend of the server.
  superset:
    image: apache/superset
    container_name: bia
    restart: always
    env_file:
      - config.env
    ports:
      - 8088:8088

# This specifies the place where the data is stored of the database.
volumes:
  postgres_db:
    driver: local
  pg_admin:
    driver: local